name: Code quality checker
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
permissions:
  contents: read
jobs:
  code-quality-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Python dependencies
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/dev.txt') }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Check up-to-date syntax of Python files
        run: pyupgrade --py312-plus **/*.py
      - name: Check format of Python files
        run: black --check .
      - name: Check import order of Python files
        run: isort -c --profile black .
      - name: Check type hints of Python files
        run: mypy --strict
      - name: Check lints of Python files.
        run: pylint
